### ISSUE TITLE
Masa全家桶Forge移植版模组名称征集 | Masa's mods forge port name collection

### ISSUE THREAD

**Issue by TexBlock** [ThinkingStudios/MaLiLib-Forge#1]
Masa's mod Forge port:
- [x] MaLiLib -> MaFgLib
- [x] Litematica -> Forgematica （全息蓝图）
- [x] MiniHUD -> BoccHUD [Bocchi + HUD] （孤独HUD）
- [x] Tweakeroo -> Tweakerge [Tweakeroo + Forge]
- [x] Item Scroller -> Rock'n Roller
- [x] Servux -> Serry [Server + STARRY]

---

如果你对于模组名称有好的想法可以在此提出。

回复格式为：
【原模组名称】-> 【移植版模组名称】

If you have a good idea for a mod name you can suggest it here.

The response format is:
[Original Mod Name] -> [Forge Port Mod Name]

**Comment by Kasualix** [comment]
TellMe 不是支持 Forge 高版本的嘛（？

**Comment by TexBlock** [comment]
> TellMe 不是支持 Forge 高版本的嘛（？

草，已删除

**Comment by snpdzk** [comment]
item scroller -> ipnscroller (forge批量合成只能用ipn）

**Comment by TexBlock** [comment]
> item scroller -> ipnscroller (forge批量合成只能用ipn）

不同意，因为不应有其他模组的名字，这容易产生混淆

**Comment by Kasualix** [comment]
servux → [starry](https://zh.moegirl.org.cn/STARRY)
（逃

**Comment by TexBlock** [comment]
> servux → [starry](https://zh.moegirl.org.cn/STARRY) （逃

草，STARRY

**Comment by snpdzk** [comment]
item scroller -> itemsnp(hsds特别喜欢喷射snp）

**Comment by TexBlock** [comment]
> item scroller -> itemsnp(hsds特别喜欢喷射snp）

细说hsds的snp（

**Comment by snpdzk** [comment]
shi niao pi（（（

**Comment by RawDiamondMC** [comment]
MaLiLib -> MaFoLib
原来MaLiLib念起来很顺的，妈里力b
MaFgLib怎么念？妈？？力b
MaLiLib是 Masa's Litemod Library的简称，Masa也没用MaLmLib啊（
个人感觉把Fg改成Fo念起来要顺一点（（（

**Comment by TexBlock** [comment]
> MaLiLib -> MaFoLib 原来MaLiLib念起来很顺的，妈里力b MaFgLib怎么念？妈？？力b MaLiLib是 Masa's Litemod Library的简称，Masa也没用MaLmLib啊（ 个人感觉把Fg改成Fo念起来要顺一点（（（

MaFg(Forge)Lib

**Comment by RawDiamondMC** [comment]
> > MaLiLib -> MaFoLib 原来MaLiLib念起来很顺的，妈里力b MaFgLib怎么念？妈？？力b MaLiLib是 Masa's Litemod Library的简称，Masa也没用MaLmLib啊（ 个人感觉把Fg改成Fo念起来要顺一点（（（
> 
> MaFg(Forge)Lib

这个蛮容易看出来的（（

我的建议就是取Forge中的F、o两个字母，念起来也顺
