### ISSUE TITLE
[BUG] 1.20 Crash when loading

### ISSUE THREAD

**Issue by Cactusstudent** [ThinkingStudios/MaLiLib-Forge#12]
hmm……真的出崩溃了
Minecraft 版本：1.20.1
Forge 版本：47.0.19
模组：Mafglib，Forgematica（版本均为0.1.0）
日志（latest.log）：https://mclo.gs/qbsFvUl
（debug.log）:https://mclo.gs/JWUpluh

**Comment by Cactusstudent** [comment]
加油，Textrue，你是最棒的（）

**Comment by TexBlock** [comment]
i will fix in somedays, thanks your issue!

**Comment by TexBlock** [comment]
fixed in latest version
