### ISSUE TITLE
Crash and a question

### ISSUE THREAD

**Issue by ScarletSM** [ThinkingStudios/MaLiLib-Forge#13]
I saw that you already had a ticket saying the same thing. Whenever I launch the game for 1.20 the game crashes. However. I was wanting to know if there was any current way I could fix this while you work on the issue? I was also wondering if there was anyway I could support the project. Forgematica is very helpful to me.

**Comment by TexBlock** [comment]
I don't have a lot of free time right now, but should be fixing it tonight.

I will close this issue because it is duplicated with #12.
