### ISSUE TITLE
[1.20]打开游戏时崩溃

### ISSUE THREAD

**Issue by xlxyvergil** [ThinkingStudios/MaLiLib-Forge#14]
[错误报告-2023-7-1_20.09.31.zip](https://github.com/ThinkingStudios/MaLiLib-Forge/files/11925827/-2023-7-1_20.09.31.zip)
用的PCL启动

**Comment by TexBlock** [comment]
模组版本？崩溃日志里没有显示mafglib的版本

**Comment by xlxyvergil** [comment]
模组版本是 0.1.1-mc1.20.1 
forge版本是 46.0.14 
目前在1.20.1版本内使用没问题，只是服务端装上会崩 Forgematica 单独装在服务端上需要前置
[crash-2023-07-08_22.30.35-fml.txt](https://github.com/ThinkingStudios/MaLiLib-Forge/files/11990864/crash-2023-07-08_22.30.35-fml.txt)
forge版本是 47.1.0 模组版本 MaFgLib-0.1.1-mc1.20.1

**Comment by TexBlock** [comment]
> 只是服务端装上会崩 Forgematica 单独装在服务端上需要前置

服务端不需要装，这是个客户端模组

**Comment by TexBlock** [comment]
单独安装时无法复现，请提供完整的模组列表

**Comment by Kasualix** [comment]
https://github.com/ThinkingStudios/MaLiLib-Forge/issues/17#issuecomment-1636644455

**Comment by TexBlock** [comment]
FIXED
