### ISSUE TITLE
[1.19.2] mod服务端无法正常运行

### ISSUE THREAD

**Issue by fenlincao** [ThinkingStudios/MaLiLib-Forge#19]
当我在服务端加入全息蓝图mod后，出现缺少前置报错，但再加上此前置mod后依旧报错，日志在下方。另外，当在forge服务端43.2.6运行全息蓝图mod时不需要前置而且可以正常运行，但在超过43.2.6的forge服务端上运行则提示需要加入前置，而加入前置后却仍然报错。
感谢！
MaFgLib/MaLiLib-Forge版本：0.1.6-mc1.19.2
日志：
[latest.log](https://github.com/ThinkingStudios/MaLiLib-Forge/files/12067070/latest.log)

**Comment by TexBlock** [comment]
但mafglib和forgematica不用装服务端上啊，你只需要在客户端装好就行，不需要在服务端装

**Comment by fenlincao** [comment]
啊这
好的 多谢
