### ISSUE TITLE
No KeyBindings in game settings?

### ISSUE THREAD

**Issue by MrEizy** [ThinkingStudios/MaLiLib-Forge#22]
1.20.1 Version have no binds it registers mod but it dont do anything, true story

**Comment by TexBlock** [comment]
Did you know that litematica's keybindings aren't set at the vanilla keybindings?

**Comment by BastianSanche0** [comment]
@TexBlock  is there anyway for users to get around the keybindings issue? I also cannot see the options within game settings nor do any keys on my keyboard seem to open its menu

**Comment by TexBlock** [comment]
> I also cannot see the options within game settings nor do any keys on my keyboard seem to open its menu

The keybindings are set in the settings of this mod. Masa's mods are all over the place.

**Comment by WeaselOnaStick** [comment]
Would appreciate if this mod didn't stick out having it's own entire keybind system when minecraft already has one. This makes it incompatible with mods like [Keybind Atlas](https://www.curseforge.com/minecraft/mc-mods/keybind-atlas) or [Keybind Bundles](https://www.curseforge.com/minecraft/mc-mods/keybind-bundles)
