### ISSUE TITLE
1.20.1 Forge Crash

### ISSUE THREAD

**Issue by SouthernPixelYT** [ThinkingStudios/MaLiLib-Forge#25]
When using...
Forgematica-0.1.2-mc1.20.1
MaFgLib-0.1.2-mc1.20.1
Tweakerge-0.1.0-mc1.20.1

The game attempts to load but crashes the game.
here is my "Latest.log"

[latest.log](https://github.com/ThinkingStudios/MaLiLib-Forge/files/13476634/latest.log)

**Comment by SouthernPixelYT** [comment]
Apparently when I attempt to load the game with just these mods it says im missing MaFgLib-0.1.2-mc1.20.1 despite me having it in the mods folder that its using to load the mods 
![Lib](https://github.com/ThinkingStudios/MaLiLib-Forge/assets/105022650/f814fac8-6895-4709-82e7-8eb3facf353e)
[latest.log](https://github.com/ThinkingStudios/MaLiLib-Forge/files/13476774/latest.log)

**Comment by TexBlock** [comment]
please download mafglib latest version

**Comment by VinDustVSD** [comment]
> please download mafglib latest version

That not working, still "Mod ID: 'mafglib', Requested by: 'forgematica', Expected range: '*', Actual version: '[MISSING]'", but latest ("MaFgLib-Alpha-0.1.2-mc1.20.jar") in mods folder.

**Comment by TexBlock** [comment]
> > please download mafglib latest version
> 
> That not working, still "Mod ID: 'mafglib', Requested by: 'forgematica', Expected range: '*', Actual version: '[MISSING]'", but latest ("MaFgLib-Alpha-0.1.2-mc1.20.jar") in mods folder.

MaFgLib latest version is 0.1.8-mc1.20.1
