### ISSUE TITLE
"MaLiLib Forge" encountered an error while running on the server

### ISSUE THREAD

**Issue by mowenxuan** [ThinkingStudios/MaLiLib-Forge#28]
Language English:1.19.2 Unable to run on server, client can run. The following are logs and reports
Language Chinese:1.19.2无法在服务器上运行,客户端可以运行以下是日志与报告
log:[日志与报告.zip](https://github.com/ThinkingStudios/Tweakeroo-Forge/files/13694660/default.zip)
Error:Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered

**Comment by TexBlock** [comment]
THIS MOD ONLY RUNNING ON CLIENT!!
