### ISSUE TITLE
[1.19.4]打开背包闪退

### ISSUE THREAD

**Issue by anjing0103** [ThinkingStudios/MaLiLib-Forge#3]
[minecraft-exported-crash-info-2023-04-30T17-35-12.zip](https://github.com/ThinkingStudios/Litematica-Forge/files/11360999/minecraft-exported-crash-info-2023-04-30T17-35-12.zip)
这个是报错日志，我把全部mod都关掉，只留下投影莫得，都会导致闪退，但是我关掉投影mod及其前置mod，就不闪退了，希望您可以解决这个问题

**Comment by TexBlock** [comment]
前置mixin问题，issue将移动至MaFgLib

**Comment by TexBlock** [comment]
在Forge1.19.4正式版出来前，暂不更新1.19.4，此issue仍被保留

**Comment by TexBlock** [comment]
已修复
https://github.com/ThinkingStudios/MaLiLib-Forge/releases/tag/v0.1.5-mc1.19.4
