### ISSUE TITLE
Version for 1.19.2 gives me an error stating "mod litematica requires malilib any - Currently, malilib is not installed"

### ISSUE THREAD

**Issue by thenameistony** [ThinkingStudios/MaLiLib-Forge#30]
I have MaFgLib installed, but the 1.19.2 version is still giving me this error. I have attached the crash report.
[crash-2024-01-13_19.55.56-fml.txt](https://github.com/ThinkingStudios/MaLiLib-Forge/files/13930259/crash-2024-01-13_19.55.56-fml.txt)
If it makes a difference, I am installing this using Curseforge, and adding it to an already established modpack (Farming Crossing 3)

**Comment by thenameistony** [comment]
I believe I posted this to the wrong Curseforge, but I'll leave it here anyways.

**Comment by thenameistony** [comment]
Wrong github, rather.

**Comment by GaPrVi** [comment]
> I have MaFgLib installed, but the 1.19.2 version is still giving me this error. I have attached the crash report. [crash-2024-01-13_19.55.56-fml.txt](https://github.com/ThinkingStudios/MaLiLib-Forge/files/13930259/crash-2024-01-13_19.55.56-fml.txt) If it makes a difference, I am installing this using Curseforge, and adding it to an already established modpack (Farming Crossing 3)

Curseforge downloads release 0.1.5 by default - it asks for malilib, and 0.1.6 already asks for MaFgLib (but this library breaks some rewritten mods)
![image](https://github.com/ThinkingStudios/MaLiLib-Forge/assets/107325712/b3a9d21f-b786-4fda-bd8d-ff6ec93ea565)

**Comment by TexBlock** [comment]
fixed in 0.1.8-mc1.19.2
