### ISSUE TITLE
The mod files are missing

### ISSUE THREAD

**Issue by ItsScappy** [ThinkingStudios/MaLiLib-Forge#34]
![Screenshot (89)](https://github.com/ThinkingStudios/MaLiLib-Forge/assets/157193966/ed5df772-13a0-427a-8d84-bd2e0186279d)

**Comment by luluxiaoyu** [comment]
the same problems
IN 1.20.1

**Comment by Pixelssssss** [comment]
Same issue here, my version is 1.19.2 :/

**Comment by luluxiaoyu** [comment]
> Same issue here, my version is 1.19.2 :/

It seems that reducing one version can be used

**Comment by TexBlock** [comment]
fixed in newer version
