### ISSUE TITLE
0.1.6-mc1.20.1 crash + FIX (neoforge) 

### ISSUE THREAD

**Issue by AsheX1** [ThinkingStudios/MaLiLib-Forge#38]
that last version crashes on neoforge
i do not know if it crashs on forge and im not testing forge but if it does this may also fix it for others

the fix is very simple
open the jar as a zip file go in META-INF folder and delete this in the mods.toml file (open mods.toml using a text editor not notepad use notepad++ or something)

delete this from the file

[[mods]]
modId = "malilib"
version = "0.1.5"
displayName = "MaFgLib (old modid compat)"
description = '''
MaFgLib old modid compat
'''

then save it and replace it the jar

**Comment by AsheX1** [comment]
and here is the file it self if editing is to hard for some you still gone have to put in the jar
https://www.dropbox.com/scl/fi/1pgwr974bz3f3qnsab75c/mods.toml?rlkey=kcuam8hrry5ebbje0d2hrbsbb&dl=1

**Comment by AsheX1** [comment]
here is the jar file with the edit mods.toml in it https://www.dropbox.com/scl/fi/tvsre7td0mr4kjbhw721r/MaFgLib-0.1.6-mc1.20.1.jar?rlkey=gj8d6lrassn8o9s6orgj74cug&dl=1

**Comment by TexBlock** [comment]
fixed in `0.1.7-mc1.20.1`
