### ISSUE TITLE
1.20.1 beta does not work 

### ISSUE THREAD

**Issue by Laboia** [ThinkingStudios/MaLiLib-Forge#39]
it doesnt register it as malilib and i cant play 
![Screenshot 2024-02-10 205715](https://github.com/ThinkingStudios/MaLiLib-Forge/assets/135391999/cea915e9-58d0-4628-82ef-43fa8eb5293d)
![Screenshot 2024-02-10 205734](https://github.com/ThinkingStudios/MaLiLib-Forge/assets/135391999/ed30dd10-6497-44d3-8bd4-e7cd5bc228a8)

**Comment by TexBlock** [comment]
install Forgematica & MaFglib latest version
