### ISSUE TITLE
Issues using Forgematica and MaFgLib on Bisect servers.

### ISSUE THREAD

**Issue by EgirlCosmo** [ThinkingStudios/MaLiLib-Forge#40]
Hello. So I recently made a Minecraft 1.20.1 server for me and my friends to play on, one requested that I download Litematica to the server, but since its forge having to use Forgematica is the only way- Since downloading it and implementing both mods. I attempt to launch the server but am met with a failure and crash with the only info being given is "Failure messageMaFgLib (MaFgLib) has failed to load correctly, java.lang.RuntimeExceptionattempted to load class. mod version0.1.3-mc1.20.1, Mod Issue URL NOT PROVIDED."     

Extra Info: MaFgLib version 0.1.3 & Forgematica version 0.1.2 with Minecraft 1.20.1 / Forge 40.2.0

**Comment by TexBlock** [comment]
mafglib & forgematica are client mod
