### ISSUE TITLE
Not loading a server on 1.19.2 (modded)

### ISSUE THREAD

**Issue by IAmFacebook** [ThinkingStudios/MaLiLib-Forge#42]
When i try booting a MP modded server up using 1.19.2 using Forgematica it says i need MaFgLib, so i added the latest 1.19.2 release then it says it failed to load so i goto a lower version. When i go to 1.7 and lower it says it needs MafgLib to use forgematica but when i add anything higher than 1.7 it says it failed to load. Pastebin for 0.1.7 and higher > https://pastebin.com/ZFDrf26T.

**Comment by TexBlock** [comment]
MaFgLib & Forgematica are only client
