### ISSUE TITLE
0.1.10-mc1.20.1 crashes on startup

### ISSUE THREAD

**Issue by WimpieRatte** [ThinkingStudios/MaLiLib-Forge#44]
When I update MaFgLib to 0.1.10, my game crashes on startup.
The first crash report was when I had all my resource packs selected.
The second crash report was when I had no resource packs selected.

Not sure how this update affects BlockEntityRenderers, but it's definitely breaking something that wasn't broken with 0.1.9
[crash-2024-05-23_09.32.38-client.txt](https://github.com/ThinkingStudios/MaLiLib-Forge/files/15413938/crash-2024-05-23_09.32.38-client.txt)
[crash-2024-05-23_10.16.00-client.txt](https://github.com/ThinkingStudios/MaLiLib-Forge/files/15413942/crash-2024-05-23_10.16.00-client.txt)

**Comment by TexBlock** [comment]
I'm in the process of refactoring parts of the code, and these changes include some breaking changes.

**Comment by WimpieRatte** [comment]
Thanks for the fix! :D
