### ISSUE TITLE
cant play singleplayer or join servers

### ISSUE THREAD

**Issue by PixelKing99** [ThinkingStudios/MaLiLib-Forge#47]
when loading a fresh instance of 1.20.6 with only this mod, if i try to join a single player world it gives me this internal exception about how it failed to encode
 a packet and then takes me back to the server list for some reason. also i checked and the same happens for servers aswell
![image](https://github.com/ThinkingStudios/MiniHUD-Forge/assets/82604822/fb24b827-d71d-4d39-966d-38a282766626)

neoforge 20.6.119
mod: MaFgLib-0.1.9-mc1.20.6.jar

**Comment by TexBlock** [comment]
mafglib issue

**Comment by PixelKing99** [comment]
where should i put this then cause on modrinth the report issues link takes me to this project

**Comment by TexBlock** [comment]
fixed in 0.1.10
