### ISSUE TITLE
Network Protocol Error with 1.20.6 and above

### ISSUE THREAD

**Issue by 20ljh** [ThinkingStudios/MaLiLib-Forge#49]
Minecraft Version : 1.21
NeoForge Version : neoforge-21.0.37-beta
MaFgLib Version : 0.1.14-mc1.21
Forgematica Version : 0.1.6-mc1.21

First of all, I apologize using translator. 
When I joined NeoForge server with MaFgLib mod and Forgematica mod(server doesn’t have these mod, only client has these mod), network protocol error has occurred. But they work in singleplayer world. Also I tried NeoForge 21.0.81-beta version, but same error occurred.
Thanks for all your hard work.

Log files:
https://gist.github.com/20ljh/531b5a76027939c0133cc1ffd22c31ac

**Comment by TexBlock** [comment]
Currently you have to install NeoNetwork on the server, which you can download from modrinth

We will fix this in the future

**Comment by 20ljh** [comment]
I installed ‘NeoNetwork-0.1.5’ on the server and checked that NeoNetwork was successfully loaded through the console message. But same error has occurred. So I also tried installing NeoNetwork on client as well, error wasn’t fixed.

**Comment by TexBlock** [comment]
It's fixed, I've replaced NeoNetwork with BadPackets
