### ISSUE TITLE
[1.18.x] the game is crashing with the opening of the inventory 

### ISSUE THREAD

**Issue by Satiras1** [ThinkingStudios/MaLiLib-Forge#5]
First of all a big "Thank you" that you worked on a port of this mod.
Now the problem:
The games starts normal, all is working. I can load schematics and place block, but when I press "e" (open the inventory) the game crashes, the world saves and I get the exit error -1. 
I tried both survival and creativ mode. There are no other mods on it for the test.
I am playing on the 1.18.2 version. 
Just now I also tried the 1.19.2 version. - This on is working without any problems...
I have no clue about coding, but I unzipt both files and saw that the 1.19.2 version has more files than the 1.18.2

**Comment by TexBlock** [comment]
crash report?

**Comment by Satiras1** [comment]
[crash-2023-05-26_16.20.59-client.txt](https://github.com/ThinkingStudios/Litematica-Forge/files/11576142/crash-2023-05-26_16.20.59-client.txt)

You mean this right?

**Comment by TexBlock** [comment]
This is MaFgLib issue, i will transfer this issue to MaFgLib

**Comment by TexBlock** [comment]
fixed in [0.1.4fix-mc1.18.2](https://modrinth.com/mod/mafglib/version/0.1.4fix-mc1.18.2)
