### ISSUE TITLE
0.1.19-mc1.21 don't support tweakeroo-foege at 0.1.4-mc1.21

### ISSUE THREAD

**Issue by Neko-Yukari** [ThinkingStudios/MaLiLib-Forge#55]
![image](https://github.com/user-attachments/assets/2ec06741-f857-497e-b9d7-e0acbfd1de83)
As in the picture, if i use these version of mods they just crashed, but when i downgrade Malilib-Forge to 0.1.18-mc1.21 the problem was fixed.
Here are crashed report and latest log
[crash-2024-08-01_13.29.36-fml.txt](https://github.com/user-attachments/files/16450763/crash-2024-08-01_13.29.36-fml.txt)
[latest.log](https://github.com/user-attachments/files/16450764/latest.log)

**Comment by TexBlock** [comment]
fixed
