### ISSUE TITLE
1.20版本mc无法启动

### ISSUE THREAD

**Issue by lingxiayangxiao** [ThinkingStudios/MaLiLib-Forge#56]
1.20版本的mc不知道为什么启动不了，我在试过1.19.2与1.20.1均正常，但是1.20直接就是游戏无法打开
[错误报告-2024-8-6_20.57.37.zip](https://github.com/user-attachments/files/16510648/-2024-8-6_20.57.37.zip)
我不知道这个错误报告是不是有用

**Comment by TexBlock** [comment]
> 1.20版本的mc不知道为什么启动不了，我在试过1.19.2与1.20.1均正常，但是1.20直接就是游戏无法打开 [错误报告-2024-8-6_20.57.37.zip](https://github.com/user-attachments/files/16510648/-2024-8-6_20.57.37.zip) 我不知道这个错误报告是不是有用

可不可以在发一遍，我这没办法下载
